// ============================================================
// data.js — 銘柄マスタ / ニュース / 市場指数のデータ層
// 本番では fetch() で外部APIに差し替え可能な構造にしてあります。
// ============================================================

// --- 主要日本株マスタ（コード / 銘柄名 / 業種 / 関連キーワード）---
const STOCK_MASTER = [
  { code: "7203", name: "トヨタ自動車",       sector: "自動車",     keywords: ["トヨタ", "EV", "ハイブリッド", "自動車"] },
  { code: "6758", name: "ソニーグループ",     sector: "電機",       keywords: ["ソニー", "ゲーム", "PlayStation", "半導体", "イメージセンサー"] },
  { code: "9984", name: "ソフトバンクG",      sector: "情報・通信", keywords: ["ソフトバンク", "孫正義", "AI", "Arm", "ビジョンファンド"] },
  { code: "6861", name: "キーエンス",         sector: "電機",       keywords: ["キーエンス", "FAセンサー", "factory automation"] },
  { code: "8035", name: "東京エレクトロン",   sector: "電機",       keywords: ["東京エレクトロン", "半導体製造装置", "半導体"] },
  { code: "6098", name: "リクルートHD",       sector: "サービス",   keywords: ["リクルート", "Indeed", "求人", "HR"] },
  { code: "9433", name: "KDDI",               sector: "情報・通信", keywords: ["KDDI", "au", "通信", "5G"] },
  { code: "9432", name: "NTT",                sector: "情報・通信", keywords: ["NTT", "ドコモ", "通信", "光回線"] },
  { code: "8306", name: "三菱UFJ FG",         sector: "銀行",       keywords: ["三菱UFJ", "銀行", "金利", "メガバンク"] },
  { code: "8316", name: "三井住友FG",         sector: "銀行",       keywords: ["三井住友", "銀行", "金利", "メガバンク"] },
  { code: "8411", name: "みずほFG",           sector: "銀行",       keywords: ["みずほ", "銀行", "金利", "メガバンク"] },
  { code: "6501", name: "日立製作所",         sector: "電機",       keywords: ["日立", "ルマーダ", "DX", "インフラ"] },
  { code: "6902", name: "デンソー",           sector: "自動車",     keywords: ["デンソー", "車載", "半導体", "自動車部品"] },
  { code: "7267", name: "ホンダ",             sector: "自動車",     keywords: ["ホンダ", "EV", "二輪", "自動車"] },
  { code: "7974", name: "任天堂",             sector: "その他製品", keywords: ["任天堂", "Switch", "ゲーム", "マリオ"] },
  { code: "4063", name: "信越化学工業",       sector: "化学",       keywords: ["信越化学", "シリコンウエハー", "半導体材料"] },
  { code: "4502", name: "武田薬品工業",       sector: "医薬品",     keywords: ["武田", "製薬", "新薬", "医薬品"] },
  { code: "4519", name: "中外製薬",           sector: "医薬品",     keywords: ["中外製薬", "ロシュ", "抗体医薬", "医薬品"] },
  { code: "9983", name: "ファーストリテイリング", sector: "小売", keywords: ["ユニクロ", "ファーストリテイリング", "アパレル", "小売"] },
  { code: "8058", name: "三菱商事",           sector: "商社",       keywords: ["三菱商事", "総合商社", "資源", "配当"] },
  { code: "8001", name: "伊藤忠商事",         sector: "商社",       keywords: ["伊藤忠", "総合商社", "バフェット", "配当"] },
  { code: "6594", name: "ニデック",           sector: "電機",       keywords: ["ニデック", "日本電産", "モーター", "EV"] },
  { code: "6367", name: "ダイキン工業",       sector: "機械",       keywords: ["ダイキン", "空調", "エアコン"] },
  { code: "7741", name: "HOYA",               sector: "精密機器",   keywords: ["HOYA", "EUV", "マスクブランクス", "半導体"] },
  { code: "4661", name: "オリエンタルランド", sector: "サービス",   keywords: ["オリエンタルランド", "ディズニー", "テーマパーク"] },
];

// --- 市場指数 ---
const MARKET_INDICES = [
  { name: "日経平均株価", value: 39845.32, change: +312.45, changePct: +0.79 },
  { name: "TOPIX",       value: 2756.18,  change: -8.42,   changePct: -0.30 },
  { name: "グロース250",  value: 642.07,   change: +5.31,   changePct: +0.83 },
  { name: "ドル円",       value: 156.84,   change: +0.42,   changePct: +0.27 },
];

// --- ニュース（relatedCodes で銘柄に紐付け）---
// publishedAt は ISO 文字列。category: 決算 / 業界 / 市場 / 経済 / 個別
const NEWS_FEED = [
  {
    id: "n01",
    title: "トヨタ、次世代EV向け全固体電池を2027年実用化へ　航続距離1000km視野",
    summary: "トヨタ自動車は次世代EVに搭載する全固体電池の量産計画を前倒しすると発表。充電時間の大幅短縮と航続距離の延伸で競争力強化を狙う。",
    source: "日経ビジネス",
    category: "個別",
    publishedAt: "2026-06-28T08:15:00+09:00",
    sentiment: "positive",
    relatedCodes: ["7203", "6902"],
  },
  {
    id: "n02",
    title: "半導体製造装置3社、AI需要で受注最高　東京エレクトロンは上方修正",
    summary: "生成AI向けの先端半導体投資が活発化し、東京エレクトロンなど製造装置メーカーの受注が過去最高水準に。通期見通しを引き上げた。",
    source: "ロイター",
    category: "業界",
    publishedAt: "2026-06-28T07:40:00+09:00",
    sentiment: "positive",
    relatedCodes: ["8035", "4063", "7741"],
  },
  {
    id: "n03",
    title: "ソフトバンクG、Armが時価総額で過去最高　AI半導体期待が追い風",
    summary: "傘下のArm株が急伸し、ソフトバンクグループの保有資産価値が膨らんだ。AI関連の設計需要拡大で市場の評価が高まっている。",
    source: "Bloomberg",
    category: "個別",
    publishedAt: "2026-06-28T06:55:00+09:00",
    sentiment: "positive",
    relatedCodes: ["9984"],
  },
  {
    id: "n04",
    title: "日銀、追加利上げ観測強まる　メガバンク株に資金流入",
    summary: "金融政策正常化への思惑から長期金利が上昇。利ざや改善期待で三菱UFJ、三井住友、みずほのメガバンク3行に買いが集まった。",
    source: "日本経済新聞",
    category: "経済",
    publishedAt: "2026-06-28T06:30:00+09:00",
    sentiment: "positive",
    relatedCodes: ["8306", "8316", "8411"],
  },
  {
    id: "n05",
    title: "ソニーG、ゲーム部門が好調　PS5後継機の開発を正式表明",
    summary: "ソニーグループはゲーム&ネットワークサービス事業が堅調と発表。次世代機の開発を進めていることを明らかにした。",
    source: "ITmedia",
    category: "個別",
    publishedAt: "2026-06-27T19:20:00+09:00",
    sentiment: "positive",
    relatedCodes: ["6758"],
  },
  {
    id: "n06",
    title: "任天堂、新型Switch向けソフトのラインナップ拡充　年末商戦に照準",
    summary: "任天堂は次世代ゲーム機向けの大型タイトルを複数投入する方針。年末商戦に向けハード・ソフト両面で攻勢をかける。",
    source: "ファミ通",
    category: "個別",
    publishedAt: "2026-06-27T17:05:00+09:00",
    sentiment: "neutral",
    relatedCodes: ["7974"],
  },
  {
    id: "n07",
    title: "円安進行で156円台　輸出関連株に追い風、自動車・電機が買われる",
    summary: "ドル円が156円台後半まで円安が進み、輸出採算の改善期待からトヨタやソニーなど輸出関連銘柄が幅広く買われた。",
    source: "時事通信",
    category: "市場",
    publishedAt: "2026-06-27T15:50:00+09:00",
    sentiment: "positive",
    relatedCodes: ["7203", "7267", "6758", "6902"],
  },
  {
    id: "n08",
    title: "ファストリ、海外ユニクロが牽引　通期営業益が過去最高更新へ",
    summary: "ファーストリテイリングは海外ユニクロ事業の好調で通期業績の上方修正を発表。北米・欧州の出店加速が寄与した。",
    source: "繊研新聞",
    category: "決算",
    publishedAt: "2026-06-27T14:10:00+09:00",
    sentiment: "positive",
    relatedCodes: ["9983"],
  },
  {
    id: "n09",
    title: "総合商社、資源価格回復で増益　三菱商事・伊藤忠が自社株買い拡大",
    summary: "資源市況の持ち直しを背景に大手商社の収益が改善。三菱商事と伊藤忠商事は株主還元の一環で自社株買いの枠を拡大した。",
    source: "日経QUICK",
    category: "業界",
    publishedAt: "2026-06-27T11:30:00+09:00",
    sentiment: "positive",
    relatedCodes: ["8058", "8001"],
  },
  {
    id: "n10",
    title: "中外製薬、新規抗体医薬が国内承認取得　ピーク時売上1500億円規模",
    summary: "中外製薬は自社創製の抗体医薬について国内製造販売承認を取得したと発表。今後の収益の柱に育てる方針。",
    source: "ミクスOnline",
    category: "個別",
    publishedAt: "2026-06-27T10:00:00+09:00",
    sentiment: "positive",
    relatedCodes: ["4519", "4502"],
  },
  {
    id: "n11",
    title: "ダイキン、インド空調市場で首位固め　新工場稼働で生産能力2倍に",
    summary: "ダイキン工業はインドの新工場が稼働し、現地生産能力を従来比2倍に拡大。成長市場での攻勢を強める。",
    source: "日刊工業新聞",
    category: "個別",
    publishedAt: "2026-06-27T09:15:00+09:00",
    sentiment: "positive",
    relatedCodes: ["6367"],
  },
  {
    id: "n12",
    title: "日立、生成AI活用のDX事業が拡大　Lumadaの受注残が積み上がる",
    summary: "日立製作所は生成AIを組み込んだDXソリューションの引き合いが増加。Lumada事業の受注残高が過去最高水準になった。",
    source: "ZDNET Japan",
    category: "業界",
    publishedAt: "2026-06-26T18:40:00+09:00",
    sentiment: "positive",
    relatedCodes: ["6501"],
  },
  {
    id: "n13",
    title: "東京市場、利益確定売りでTOPIX反落　高値警戒感が重し",
    summary: "前日までの上昇を受けて利益確定の売りが優勢に。TOPIXは小幅反落した。高値警戒感から値がさ株の一部に売りが出た。",
    source: "ロイター",
    category: "市場",
    publishedAt: "2026-06-26T15:30:00+09:00",
    sentiment: "negative",
    relatedCodes: [],
  },
  {
    id: "n14",
    title: "ニデック、EV用駆動モーター『E-Axle』の中国向け出荷が回復",
    summary: "ニデックはEV向け駆動モジュールの出荷が中国市場で持ち直したと発表。採算改善に向けたコスト構造改革も進む。",
    source: "EE Times Japan",
    category: "個別",
    publishedAt: "2026-06-26T13:20:00+09:00",
    sentiment: "neutral",
    relatedCodes: ["6594"],
  },
  {
    id: "n15",
    title: "リクルート、米Indeedの広告単価上昇　HRテック事業が再加速",
    summary: "リクルートホールディングスは米求人サイトIndeedの収益性が改善したと発表。労働市場の回復が追い風になっている。",
    source: "日経クロステック",
    category: "個別",
    publishedAt: "2026-06-26T11:05:00+09:00",
    sentiment: "positive",
    relatedCodes: ["6098"],
  },
  {
    id: "n16",
    title: "KDDIとNTT、データセンター増設を相次ぎ発表　AI需要に対応",
    summary: "通信大手2社が国内データセンターの大規模増設を発表。生成AIの普及に伴う計算需要の拡大に備える。",
    source: "日経電子版",
    category: "業界",
    publishedAt: "2026-06-26T09:50:00+09:00",
    sentiment: "positive",
    relatedCodes: ["9433", "9432"],
  },
  {
    id: "n17",
    title: "オリエンタルランド、入園者数が想定上回る　新エリア効果が継続",
    summary: "オリエンタルランドは東京ディズニーリゾートの入園者数が計画を上回ったと発表。客単価の上昇も収益を押し上げた。",
    source: "観光経済新聞",
    category: "個別",
    publishedAt: "2026-06-25T17:30:00+09:00",
    sentiment: "positive",
    relatedCodes: ["4661"],
  },
  {
    id: "n18",
    title: "キーエンス、最高益更新も高PERに警戒　機関投資家で見方分かれる",
    summary: "キーエンスは最高益を更新したが、株価のバリュエーションを巡って市場の見方が分かれている。中長期の成長性が論点。",
    source: "会社四季報オンライン",
    category: "決算",
    publishedAt: "2026-06-25T15:00:00+09:00",
    sentiment: "neutral",
    relatedCodes: ["6861"],
  },
];

// 本番APIへ差し替える場合の参考スタブ（現状は同期データを返す）
async function fetchNews() {
  // 例: const res = await fetch("/api/news"); return res.json();
  return NEWS_FEED;
}
async function fetchIndices() {
  return MARKET_INDICES;
}
